gesdinet_jwt_refresh_token: 
    refresh_token_class: App\Entity\RefreshToken
    user_provider: security.user.provider.concrete.app_user_provider_refresh_jwt_token
    user_identity_field: id
    ttl: 14400 # 4 heures